### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by MiniDigger** [KyoriPowered/MiniMessageViewer#1]
* [ ] measure out chat box exactly
* [ ] prevent overlapping hover boxes
* [ ] implement missing todos
* [x] deploy to github pages
* [x] lore display
* [ ] fix multi line hovers
